# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :build do
    xcode_select("/Applications/Xcode 2.app")
    increment_build_number(xcodeproj: "swapp.xcodeproj")
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "swapp.xcodeproj"
    )
    build_app(workspace: "swapp.xcworkspace", scheme: "swapp", xcargs: "-allowProvisioningUpdates")
  end
  lane :publish do
    upload_to_testflight
  end
end
